using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraCharts;
using System.Data.SqlClient;
using System.Configuration;
using HateksPurchasing.Helper;

namespace HateksPurchasing
{
    public partial class DashBoard : DevExpress.XtraEditors.XtraForm
    {
        public DashBoard()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            getTotalPriceByDraftTableAdapter1.Fill(hateksPurchasingDataSet1.GetTotalPriceByDraft); PrepareData();
        }

        private void PrepareData()
        {
            DataTable data = hateksPurchasingDataSet1.GetTotalPriceByDraft;
            foreach (DataRow dr in data.Rows)
            {
                chart.Series["Departmanlar"].Points.Add(new SeriesPoint(dr["DraftTypeName"], dr["Total"]));
                //  PrepareCompanies(int.Parse(dr["DraftTypeId"].ToString()));
            }



            //Companies


            ChartTitle chartTitle1 = new ChartTitle();
            chartTitle1.Text = "Departmanların Harcamaları";
            chartTitle1.WordWrap = true;
            chart.Titles.Add(chartTitle1);

        }

        private void PrepareCompanies(int id)
        {


            SqlConnection con = SqlHelper.OpenConnection();
            SqlCommand cmd = SqlHelper.GetSqlCommand("select * from GetTotalPriceByCompany() where DraftTypeId=" + id, con);
            SqlDataReader dr = SqlHelper.GetSqlDataReader(cmd);
            while (dr.Read())
            {
                chart.Series["Tedarikçiler"].Points.Add(new SeriesPoint(dr["CompanyName"], dr["TotalPrice"]));
            }
            SqlHelper.CloseConnection(con);

        }

        private void DashBoard_Load(object sender, EventArgs e)
        {


        }
    }
}